### ISSUE TITLE
Is this still updated?

### ISSUE THREAD

**Issue by SrPatinhas** [caffeinated/gamification#2]
Will this be continued or don't have plans to continue this project?

**Comment by SrPatinhas** [comment]
@kaidesu another question, as i can see, this is not with full features as it is on the example right?

**Comment by kaidesu** [comment]
The project I was working on that was going to use this was put on hold. So it's simply not on my high priority list.

And no, features have not been built out - the example usage is me brainstorming the functionality and usage of the package before jumping into development.

**Comment by SrPatinhas** [comment]
@kaidesu thanks for the answer. I would like to use this package, maybe i could make some PRs to the repo and you would help with some development? i would be high apreciated ;)

**Comment by kaidesu** [comment]
Certainly! Go for it man~

**Comment by pacoorozco** [comment]
Hi @kaidesu 

I'm developing a Gamification app in Laravel 5.1, would you be interested to contribute? I'm a bit stuck in some design questions:

https://github.com/pacoorozco/gamify-l5

This offer is opened to anyone!
Thanks in advance

**Comment by xtrasmal** [comment]
I added some code to get the party started.. 💃 
So now and then I come across this package..because I use the caffeinated/modules package a lot! You rule. So one of these days I am going to contribute more to caffeinated.
